# Generated by Django 4.0.1 on 2022-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('date', models.DateField(default=0)),
            ],
        ),
    ]
