# Generated by Django 4.0.1 on 2022-01-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
