# Generated by Django 4.0.1 on 2022-01-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
