# Generated by Django 4.0.1 on 2022-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_training_date_alter_training_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.FloatField(),
        ),
    ]
